name: lsm-quickstart
description: The Inmanta project associated with the lsm quickstart guide.
author: Inmanta
author_email: code@inmanta.com
license: Inmanta EULA
copyright: 2019 Inmanta
modulepath: libs
downloadpath: libs
repo:
  - git@github.com:inmanta/{}.git
install_mode: master
requires:
